In [1]:
import pennylane as qml
from pennylane import numpy as np
import matplotlib.pyplot as plt
import cmath

In [ ]:
from qiskit import QuantumCircuit

In [4]:
# Pauli Matries

Id = np.identity(2)
Z = np.array([[1, 0], [0, -1]])
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0,complex(0,1)],[-complex(0,1),0]])

gate_array = [Id,X,Y,Z]

In [40]:
N = 4

# 1st argument --> numbers ranging from 0 to 9, 
# 2nd argument, row = 2, col = 3
array = np.random.randint(10, size=(N, N))
print(array)

[[9 0 7 8]
 [8 1 1 0]
 [3 0 5 4]
 [2 0 5 8]]


In [49]:
counter = 0
i = 0

combination = gate_array
temp_array = gate_array

while counter < np.log2(len(array)) - 1:

    combination = np.kron(combination, gate_array)
    
    counter += 1

In [50]:
#combination

In [52]:
final_array = np.zeros((len(array),len(array)), dtype=complex)
coeff = np.zeros((len(array)**2), dtype=complex)

for i in range(len(combination)):
    coeff[i] =  1/(len(array)) * np.matrix.trace(np.matmul(array,combination[i]))
    final_array +=  coeff[i] * combination[i]

In [53]:
coeff

tensor([ 5.75+0.j  ,  4.25+0.j  ,  0.  +2.25j,  1.25+0.j  ,  2.5 +0.j  ,
         2.75+0.j  ,  0.  -1.25j,  2.5 +0.j  ,  0.  -1.j  ,  0.  -1.75j,
        -2.25+0.j  ,  0.  -1.j  , -0.75+0.j  , -0.25+0.j  ,  0.  +1.75j,
         2.75+0.j  ], requires_grad=True)

In [54]:
final_array == array

tensor([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]], requires_grad=True)

$$A_1 = \sum^{A_{1_j}}$$

\begin{align*}
        A |\Psi\rangle    &= \lambda |\Psi\rangle\\
        (\hat{c}_1 A_1 + \hat{c}_2 A_2 + ... + \hat{c}_n A_n) |\Psi\rangle    &= (\lambda_1 + \lambda_2 + \lambda_n) |\Psi\rangle\\
        \hat{c}_1 A_1 (d_1 V_1 + d_2 V_2 + ... + d_n V_n)   &= (\lambda_1 + \lambda_2 + ... + \lambda_n) |\Psi\rangle\\
        \sum c_1 A_1 |\Psi\rangle_n &= \sum \lambda_n |\Psi\rangle_n \\
\end{align*}

$$A |\Psi\rangle = \lambda |\Psi\rangle$$
$$(A - I \lambda)|\Psi\rangle = 0$$

Find 

In [64]:
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from math import pi

import matplotlib.pyplot as plt

from qiskit.tools.visualization import plot_histogram
from qiskit_aer.primitives import Sampler

Want to solve for $c_1$ with $A_1$:

In [65]:
# First Coefficient and Unitary matrix

coeff_1 = coeff[0]
A_1 = combination[0]

print(coeff_1, "\n")
print(A_1)

(5.75+0j) 

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


In [67]:
# Unitary Test

A_1_daggar = A_1.dot(A_1.conj().T)

A_1 == A_1_daggar

tensor([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]], requires_grad=True)

In [47]:
nq = 3    # number of qubits
m = 3    # number of classical bits
q = QuantumRegister(nq,'q')
c = ClassicalRegister(m,'c')

qc = QuantumCircuit(q,c)