## Constant Coefficient 

$$ ay'' + by' + cy = 0$$ where a, b, and c are constants.

In [1]:
import pennylane as qml
from pennylane import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.set_printoptions(threshold=np.inf)

In [3]:
matrix = np.zeros((32,32), dtype=float, order='C') 

With constant coefficients, solutions take the form of $y = e^{rx}$. Therefore
$$y=e^{rx} \: \Rightarrow \: y' = re^{rx} \: \Rightarrow \: y' = r^2e^{rx},$$
<br>
Where $y_i = e^{rx}$ is a solution only in the case where 
$$ar^2 + br + c = 0.$$
<br>
By utilizing the quadratic formula, two distinct, real roots, $r_1$ and $r_2$,  form the general solution
$$ y = c_1e^{r_1x} + c_2e^{r_2x}.$$
<br>
Where
$$y' = \frac{y_i -y_{i+1}}{\Delta y},$$
<br>
$$y'' = \frac{y_{i-1}-2y_i +y_{i+1}}{\Delta y^2}.$$



Consider the equation $ y'' - y' - 2y = 0.$ 
<br>
By setting $y = e^{rx}$, the equation becomes $r^2 - r - 2 = 0.$
<br>
The roots of the quadratic are real and distinct, $r_1 = -1$ and $r_2 = 2$, so the general solution becomes
$$ y = c_1e^{-x} + c_2e^{2x}.$$

The discretized form
$$\frac{y_{i-1}-2y_i +y_{i+1}}{\Delta y^2} - \frac{y_i -y_{i+1}}{\Delta y} -2y_i = 0$$
which becomes
$$\left( \frac{1}{\Delta y^2}+\frac{1}{\Delta y} \right)y_{i+1}-\left( \frac{2}{\Delta y^2}+\frac{1}{\Delta y}+2 \right)y_i + \left( \frac{1}{\Delta y^2} \right)y_{i-1} = 0$$

In [4]:
delta_y = 1

In [5]:
for i in range(len(matrix)): 
    matrix[i,i] = -(2/delta_y**2 + 1/delta_y +2)
    matrix[i,i-1] = 1/delta_y

for i in range(len(matrix)-1):
     matrix[i,i+1] = 1/delta_y**2 + 1/delta_y
    
matrix[0,-1] = 0

b = np.zeros(32)

In [6]:
matrix

tensor([[-5.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 1., -5.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1., -5.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1., -5.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1., -5.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1., -5.,  2.,  0.,  0.,  0.,  

In [7]:
b

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

In [8]:
np.linalg.solve(matrix, b)

tensor([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0.], requires_grad=True)