## Discretizing 2D Poisson's Equation with Finite DIfference

$$ \frac{\partial^2 u}{\partial x^2}
      + \frac{\partial^2 u}{\partial y^2}= f(x,y)$$ 
Using the finite differences method to discretize the 2D Poisson's Equation.

In [1]:
import pennylane as qml
from pennylane import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.set_printoptions(threshold=np.inf)

In [3]:
matrix = np.zeros((32,32), dtype=float, order='C') 

it is known that
$$\Delta u=\frac{\partial^2 u}{\partial x^2}
      + \frac{\partial^2 u}{\partial y^2}$$
$$\approx \frac{u_{(i+1)j}-2u_{ij} +u_{(i-1)j}}{\Delta x^2} + \frac{u_{i(j+1)}-2u_{ij} +u_{i(j-1)}}{\Delta y^2}.$$
Therefore
$$ \frac{u_{(i+1)j}-2u_{ij} +u_{(i-1)j}}{\Delta x^2} + \frac{u_{i(j+1)}-2u_{ij} +u_{i(j-1)}}{\Delta y^2} =f(x,y).$$ 

Assuming a uniform spatial discretization, $\Delta x^2 = \Delta y^2$. Thus
$$ \frac{1}{\Delta x^2} \left(u_{(i+1)j}+u_{(i-1)j}-4u_{ij} +u_{i(j+1)} +u_{i(j-1)}\right) =f_{ij}.$$ 
<br>
As a result, the following linear system is produced
$$Au = b.$$

In [4]:
delta_y = 1
delta_x = 1
f = 1

In [5]:
for i in range(len(matrix)): 
    matrix[i,i] = -4/delta_x**2
    matrix[i,i-1] = 1/delta_x**2
    matrix[i-1,i] = 1/delta_x**2

for i in range(len(matrix)-1):
    matrix[i,i+1] = 1/delta_x**2
    matrix[i+1,i] = 1/delta_x**2
matrix[0,-1] = 0

b = np.zeros(32)

In [6]:
matrix

tensor([[-4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 1., -4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1., -4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1., -4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1., -4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1., -4.,  1.,  0.,  0.,  0.,  

In [7]:
b

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

In [8]:
np.linalg.solve(matrix, b)

tensor([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0.], requires_grad=True)