In [91]:
import pennylane as qml
from pennylane import numpy as np
import matplotlib.pyplot as plt
import cmath

### 2x2 Matrix

In [152]:
Id = np.identity(2)
Z = np.array([[1, 0], [0, -1]])
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0,complex(0,1)],[-complex(0,1),0]])

In [218]:
A = np.array([[-4,2], [-1,-3]]) 
A

tensor([[-4,  2],
        [-1, -3]], requires_grad=True)

In [156]:
c = [complex(0,0)]*(len(A)**2)
c

[0j, 0j, 0j, 0j]

In [157]:
c[0] = 1/(len(A)) * np.matrix.trace(np.matmul(A,Id))
c[1] = 1/(len(A)) * np.matrix.trace(np.matmul(A,Z))
c[2] = 1/(len(A)) * np.matrix.trace(np.matmul(A,X))
c[3] = 1/(len(A)) * np.matrix.trace(np.matmul(A,Y)) #need this to output with the complex number

In [158]:
c

[-3.5, -0.5, 0.5, -1.5j]

In [160]:
A = c[0]*Id + c[1]*Z + c[2]*X + c[3]*Y

In [161]:
A

tensor([[-4.+0.j,  2.+0.j],
        [-1.+0.j, -3.+0.j]], requires_grad=True)

### 4x4 Matrix

In [164]:
Id = np.identity(2)
Z = np.array([[1, 0], [0, -1]])
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0,complex(0,1)],[-complex(0,1),0]])

In [165]:
#going to need to create a combination of all arrays
#first identity
Id4 = np.identity(4)

In [166]:
#Would the others be kronkers of the same together??
ZZ = np.kron(Z,Z)
XX = np.kron(X,X)
YY = np.kron(Y,Y)

In [169]:
YY

tensor([[ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j],
        [ 0.-0.j,  0.+0.j,  1.-0.j,  0.+0.j],
        [ 0.-0.j,  1.-0.j,  0.+0.j,  0.+0.j],
        [-1.+0.j,  0.-0.j,  0.-0.j,  0.+0.j]], requires_grad=True)

In [170]:
#now combinations
ZX = np.kron(Z,X)
ZY = np.kron(Z,Y)
XZ = np.kron(X,Z)
XY = np.kron(X,Y)
YZ = np.kron(Y,Z)
YX = np.kron(Y,X)

#and combinations with Identity
IdZ = np.kron(Id,Z)
IdX = np.kron(Id,X)
IdY = np.kron(Id,Y)

ZId = np.kron(Z,Id)
XId = np.kron(X,Id)
YId = np.kron(Y,Id)

#is this ok? it's going to scale exponentially...... n^2

In [179]:
A = np.matrix([[1,2,3,4],[4,3,2,1],[3,2,1,4],[2,1,3,4]])
A_4x4 = np.matrix([[1,2,3,4],[4,3,2,1],[3,2,1,4],[2,1,3,4]])

In [180]:
A_4x4

matrix([[1, 2, 3, 4],
        [4, 3, 2, 1],
        [3, 2, 1, 4],
        [2, 1, 3, 4]])

In [181]:
c = [complex(0,0)]*(len(A)**2)

In [182]:
c[0] = 1/(len(A)) * np.matrix.trace(np.matmul(A,Id4))
c[1] = 1/(len(A)) * np.matrix.trace(np.matmul(A,ZZ))
c[2] = 1/(len(A)) * np.matrix.trace(np.matmul(A,XX))
c[3] = 1/(len(A)) * np.matrix.trace(np.matmul(A,YY))

c[4] = 1/(len(A)) * np.matrix.trace(np.matmul(A,ZX))
c[5] = 1/(len(A)) * np.matrix.trace(np.matmul(A,ZY))
c[6] = 1/(len(A)) * np.matrix.trace(np.matmul(A,XZ))
c[7] = 1/(len(A)) * np.matrix.trace(np.matmul(A,XY))
c[8] = 1/(len(A)) * np.matrix.trace(np.matmul(A,YZ))
c[9] = 1/(len(A)) * np.matrix.trace(np.matmul(A,YX))

c[10] = 1/(len(A)) * np.matrix.trace(np.matmul(A,IdZ))
c[11] = 1/(len(A)) * np.matrix.trace(np.matmul(A,IdX))
c[12] = 1/(len(A)) * np.matrix.trace(np.matmul(A,IdY))

c[13] = 1/(len(A)) * np.matrix.trace(np.matmul(A,ZId))
c[14] = 1/(len(A)) * np.matrix.trace(np.matmul(A,XId))
c[15] = 1/(len(A)) * np.matrix.trace(np.matmul(A,YId))


In [183]:
A = c[0]*Id4 + c[1]*ZZ + c[2]*XX + c[3]*YY + c[4]*ZX + c[5]*ZY + c[6]*XZ + c[7]*XY + c[8]*YZ + c[9]*YX + c[10]*IdZ + c[11]*IdX + c[12]*IdY + c[13]*ZId + c[14]*XId + c[15]*YId

In [184]:
A

tensor([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
        [4.+0.j, 3.+0.j, 2.+0.j, 1.+0.j],
        [3.+0.j, 2.+0.j, 1.+0.j, 4.+0.j],
        [2.+0.j, 1.+0.j, 3.+0.j, 4.+0.j]], requires_grad=True)

In [185]:
A == A_4x4

tensor([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]], requires_grad=True)

### NxN

In [261]:
N = 8

# 1st argument --> numbers ranging from 0 to 9, 
# 2nd argument, row = 2, col = 3
array = np.random.randint(10, size=(N, N))
print(array)

[[2 9 1 8 0 9 7 4]
 [1 2 4 3 5 6 1 6]
 [4 4 3 4 4 1 4 7]
 [4 4 4 0 9 0 6 5]
 [8 4 7 1 1 0 3 5]
 [2 2 9 9 3 5 9 7]
 [1 5 8 0 3 7 1 7]
 [1 1 6 9 0 8 1 7]]


In [262]:
gate_array = [Id,X,Y,Z]

In [263]:
gate_array[3]

tensor([[ 1,  0],
        [ 0, -1]], requires_grad=True)

In [264]:
len(array)

8

In [265]:
counter = 0
i = 0

combination = gate_array
temp_array = gate_array

while counter < np.log2(len(array)) - 1:

    combination = np.kron(combination, gate_array)
    
    counter += 1

In [270]:
final_array = np.zeros((len(array),len(array)), dtype=complex)

for i in range(len(combination)):
    c =  1/(len(array)) * np.matrix.trace(np.matmul(array,combination[i]))
    final_array +=  c * combination[i]

In [271]:
final_array

tensor([[2.+0.j, 9.+0.j, 1.+0.j, 8.+0.j, 0.+0.j, 9.+0.j, 7.+0.j, 4.+0.j],
        [1.+0.j, 2.+0.j, 4.+0.j, 3.+0.j, 5.+0.j, 6.+0.j, 1.+0.j, 6.+0.j],
        [4.+0.j, 4.+0.j, 3.+0.j, 4.+0.j, 4.+0.j, 1.+0.j, 4.+0.j, 7.+0.j],
        [4.+0.j, 4.+0.j, 4.+0.j, 0.+0.j, 9.+0.j, 0.+0.j, 6.+0.j, 5.+0.j],
        [8.+0.j, 4.+0.j, 7.+0.j, 1.+0.j, 1.+0.j, 0.+0.j, 3.+0.j, 5.+0.j],
        [2.+0.j, 2.+0.j, 9.+0.j, 9.+0.j, 3.+0.j, 5.+0.j, 9.+0.j, 7.+0.j],
        [1.+0.j, 5.+0.j, 8.+0.j, 0.+0.j, 3.+0.j, 7.+0.j, 1.+0.j, 7.+0.j],
        [1.+0.j, 1.+0.j, 6.+0.j, 9.+0.j, 0.+0.j, 8.+0.j, 1.+0.j, 7.+0.j]], requires_grad=True)

In [272]:
array

tensor([[2, 9, 1, 8, 0, 9, 7, 4],
        [1, 2, 4, 3, 5, 6, 1, 6],
        [4, 4, 3, 4, 4, 1, 4, 7],
        [4, 4, 4, 0, 9, 0, 6, 5],
        [8, 4, 7, 1, 1, 0, 3, 5],
        [2, 2, 9, 9, 3, 5, 9, 7],
        [1, 5, 8, 0, 3, 7, 1, 7],
        [1, 1, 6, 9, 0, 8, 1, 7]], requires_grad=True)