In [91]:
import pennylane as qml
from pennylane import numpy as np
import matplotlib.pyplot as plt
import cmath

### 2x2 Matrix

In [92]:
Id = np.identity(2)
Z = np.array([[1, 0], [0, -1]])
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0,complex(0,1)],[-complex(0,1),0]])

In [93]:
Y

tensor([[ 0.+0.j,  0.+1.j],
        [-0.-1.j,  0.+0.j]], requires_grad=True)

In [84]:
A = np.array([[-4,2], [-1,-3]])
A

tensor([[-4,  2],
        [-1, -3]], requires_grad=True)

In [94]:
c = [complex(0,0)]*(len(A)**2)

In [100]:
c[0] = 1/(len(A)) * np.matrix.trace(np.matmul(A,Id))
c[1] = 1/(len(A)) * np.matrix.trace(np.matmul(A,Z))
c[2] = 1/(len(A)) * np.matrix.trace(np.matmul(A,X))
c[3] = 1/(len(A)) * np.matrix.trace(np.matmul(A,Y)) #need this to output with the complex number

In [101]:
c

[-3.5, -0.5, 0.5, -1.5j]

In [102]:
temp = np.matmul(A,Y)

In [111]:
A = c[0]*Id + c[1]*Z + c[2]*X + c[3]*Y

In [112]:
A

tensor([[-4.+0.j,  2.+0.j],
        [-1.+0.j, -3.+0.j]], requires_grad=True)